#######################################
# General
#######################################
# shell 
set-option -g default-shell "/opt/homebrew/bin/fish" # Set default shell to Fish
set-option -g default-command "/opt/homebrew/bin/fish" # Ensure tmux uses Fish shell

set -as terminal-overrides ",xterm-256color:RGB"
set -g mouse on
set -g history-limit 100000

set -g extended-keys on
set -as terminal-features 'xterm*:extkeys'
set -g extended-keys-format csi-u

set -g renumber-windows on
set -g set-clipboard on

#######################################
# keyboard binding
#######################################
## reload config
bind r source-file ~/.tmux.conf \; display-message "tmux config reloaded"

#######################################
# plugin
#######################################
set -g @plugin 'tmux-plugins/tpm'

# General plugins
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-copy'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-open'

# Better session management
# set -g @plugin 'tmux-plugins/tmux-resurrect'
# set -g @plugin 'tmux-plugins/tmux-continuum'


# Better navigation with vim/neovim
# set -g @plugin 'christoomey/vim-tmux-navigator'
# set -g @plugin 'tmux-plugins/tmux-pain-control'
# set -g @plugin 'tmux-plugins/tmux-prefix-highlight'

# set -g @continuum-restore 'on'
# set -g @resurrect-capture-pane-contents 'on'


## status bar
set -g base-index 1
setw -g pane-base-index 1

set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'catppuccin/tmux'
set -g @catppuccin_flavor 'mocha'

set -g @catppuccin_window_status_style "rounded"
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -agF status-right "#{E:@catppuccin_status_ram}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"
set -agF status-right "#{E:@catppuccin_status_battery}"


run '~/.config/tmux/plugins/tpm/tpm'